languages:
  PHP: true
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd_ruleset.xml"
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- tests/